In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [53]:
#load librabries for Data Analysis
import pandas as pd
import os
os.listdir('/kaggle/input/datasets/exquisiteoge/stockr/')

['Stock_Prices.csv']

In [58]:
data = pd.read_csv('/kaggle/input/datasets/exquisiteoge/stockr/Stock_Prices.csv')
data.head(5)

  symbol        date      open      high       low     close    volume
0    AAL  2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943
1   AAPL  2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957
2    AAP  2014-01-02  110.3600  111.8800  109.2900  109.7400    542711
3   ABBV  2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061
4    ABC  2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391

In [59]:
data.isnull()

        symbol   date   open   high    low  close  volume
0        False  False  False  False  False  False   False
1        False  False  False  False  False  False   False
2        False  False  False  False  False  False   False
3        False  False  False  False  False  False   False
4        False  False  False  False  False  False   False
...        ...    ...    ...    ...    ...    ...     ...
497467   False  False  False  False  False  False   False
497468   False  False  False  False  False  False   False
497469   False  False  False  False  False  False   False
497470   False  False  False  False  False  False   False
497471   False  False  False  False  False  False   False

[497472 rows x 7 columns]

In [60]:
data.isnull().sum()

symbol     0
date       0
open      11
high       8
low        8
close      0
volume     0
dtype: int64

In [61]:
data.shape

(497472, 7)

In [69]:
data_clean = data.dropna()
data_clean.isnull().sum()

symbol    0
date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [70]:
data_clean.shape

(497461, 7)

In [71]:
data_clean.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
497467    False
497468    False
497469    False
497470    False
497471    False
Length: 497461, dtype: bool

In [72]:
data_clean.duplicated().sum()

np.int64(0)

In [73]:
data_clean.head(10)

  symbol        date      open      high       low     close    volume
0    AAL  2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943
1   AAPL  2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957
2    AAP  2014-01-02  110.3600  111.8800  109.2900  109.7400    542711
3   ABBV  2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061
4    ABC  2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391
5    ABT  2014-01-02   38.0900   38.4000   38.0000   38.2300   4967472
6    ACN  2014-01-02   81.5000   81.9200   81.0900   81.1300   2405384
7   ADBE  2014-01-02   59.0600   59.5300   58.9400   59.2900   2746370
8    ADI  2014-01-02   49.5200   49.7500   49.0400   49.2800   2799092
9    ADM  2014-01-02   43.2200   43.2900   42.7900   42.9900   2753765

In [76]:
data_clean.loc[:,'date'] = pd.to_datetime(data_clean['date'])

In [77]:
data_clean.head(10)

,symbol,date,open,high,low,close,volume
0,AAL,2014-01-02 00:00:00,25.0700,25.8200,25.0600,25.3600,8998943
1,AAPL,2014-01-02 00:00:00,79.3828,79.5756,78.8601,79.0185,58791957
2,AAP,2014-01-02 00:00:00,110.3600,111.8800,109.2900,109.7400,542711
3,ABBV,2014-01-02 00:00:00,52.1200,52.3300,51.5200,51.9800,4569061
4,ABC,2014-01-02 00:00:00,70.1100,70.2300,69.4800,69.8900,1148391
5,ABT,2014-01-02 00:00:00,38.0900,38.4000,38.0000,38.2300,4967472
6,ACN,2014-01-02 00:00:00,81.5000,81.9200,81.0900,81.1300,2405384
7,ADBE,2014-01-02 00:00:00,59.0600,59.5300,58.9400,59.2900,2746370
8,ADI,2014-01-02 00:00:00,49.5200,49.7500,49.0400,49.2800,2799092
9,ADM,2014-01-02 00:00:00,43.2200,43.2900,42.7900,42.9900,2753765

In [79]:
data_clean.loc[:,'symbol'] = data_clean['symbol'].str.strip().str.title()

In [80]:
data_clean.head(10)

,symbol,date,open,high,low,close,volume
0,Aal,2014-01-02 00:00:00,25.0700,25.8200,25.0600,25.3600,8998943
1,Aapl,2014-01-02 00:00:00,79.3828,79.5756,78.8601,79.0185,58791957
2,Aap,2014-01-02 00:00:00,110.3600,111.8800,109.2900,109.7400,542711
3,Abbv,2014-01-02 00:00:00,52.1200,52.3300,51.5200,51.9800,4569061
4,Abc,2014-01-02 00:00:00,70.1100,70.2300,69.4800,69.8900,1148391
5,Abt,2014-01-02 00:00:00,38.0900,38.4000,38.0000,38.2300,4967472
6,Acn,2014-01-02 00:00:00,81.5000,81.9200,81.0900,81.1300,2405384
7,Adbe,2014-01-02 00:00:00,59.0600,59.5300,58.9400,59.2900,2746370
8,Adi,2014-01-02 00:00:00,49.5200,49.7500,49.0400,49.2800,2799092
9,Adm,2014-01-02 00:00:00,43.2200,43.2900,42.7900,42.9900,2753765

In [84]:
data_clean.loc[:,'volume'] = pd.to_numeric(data_clean['volume'],errors ='coerce' )

In [85]:
data_clean.head(10)

,symbol,date,open,high,low,close,volume
0,Aal,2014-01-02 00:00:00,25.0700,25.8200,25.0600,25.3600,8998943
1,Aapl,2014-01-02 00:00:00,79.3828,79.5756,78.8601,79.0185,58791957
2,Aap,2014-01-02 00:00:00,110.3600,111.8800,109.2900,109.7400,542711
3,Abbv,2014-01-02 00:00:00,52.1200,52.3300,51.5200,51.9800,4569061
4,Abc,2014-01-02 00:00:00,70.1100,70.2300,69.4800,69.8900,1148391
5,Abt,2014-01-02 00:00:00,38.0900,38.4000,38.0000,38.2300,4967472
6,Acn,2014-01-02 00:00:00,81.5000,81.9200,81.0900,81.1300,2405384
7,Adbe,2014-01-02 00:00:00,59.0600,59.5300,58.9400,59.2900,2746370
8,Adi,2014-01-02 00:00:00,49.5200,49.7500,49.0400,49.2800,2799092
9,Adm,2014-01-02 00:00:00,43.2200,43.2900,42.7900,42.9900,2753765

In [89]:
data_clean.to_csv("Project1.csv",index=False)

In [90]:
os.listdir()

['Project1.csv', '.virtual_documents']